language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
  - "3.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - >
    conda create -q -c conda-forge -c defaults -n Newton-Krylov_OOC python=$TRAVIS_PYTHON_VERSION
    pytest black netCDF4 numpy pyyaml gitpython scipy cf_units
  - conda activate Newton-Krylov_OOC

script:
  - black --check .
  # setup solver, with default tracer modules
  # persist not needed since driver is not invoked
  # this does perform forward model runs, since fp_cnt=2
  - ./scripts/setup_solver.sh
  # now that the workdir is populated, pytest tests have what they need
  - pytest
  # setup and run solver, do with iage only to reduce test time
  # also exercises passing --model_name to setup_solver.sh
  - ./scripts/setup_solver.sh --tracer_module_names iage --model_name test_problem --persist
  - $HOME/test_problem_work/nk_driver.sh
  # setup and run solver for multiple dye_decay tracers
  - ./scripts/setup_solver.sh --tracer_module_names "dye_decay_{suff}:001:010"
    --newton_max_iter 4 --newton_rel_tol 1.0e-6 --persist
  - $HOME/test_problem_work/nk_driver.sh
