name: Newton-Krylov_OOC
channels:
- conda-forge
- defaults
dependencies:
# development
- pip
- python=3.6
- pytest
- pylint
- black
- flake8
- pre-commit

# documentation
- sphinx
- sphinx_rtd_theme
- sphinxcontrib-bibtex

# solver requirements
- netCDF4
- numpy
- pyyaml
- gitpython

# test_problem requirements
- scipy
- pint

# cime_pop requirements
- nco

# notebooks
- jupyterlab
- matplotlib
- xarray
- nc-time-axis
